### ISSUE TITLE
Type Synonyms?

### ISSUE THREAD

**Issue by markandrus** [Gabriel439/Haskell-Dhall-Bash-Library#1]
Hi,

I am trying to use `dhall-bash` for some more strongly-typed configuration I typically consume from Bash scripts. To this end, I want to introduce type synonyms for my configuration to distinguish various types of strings. I'm not sure how to make this work, though. Can you point me in the right direction? Here is my test script, `test.dhall`:

```dhall
let MyText : Type = Text
in "Hello, World!" : MyText
```

And here is the output I receive:

```
$ dhall-to-bash < test.dhall


MyText : Type

Error: Expression doesn't match annotation

"Hello, World!" : MyText

(stdin):2:4

```

Thanks,
Mark

**Comment by Gabriella439** [comment]
This is related to the following two issues:

* https://github.com/dhall-lang/dhall-haskell/issues/10
* https://github.com/dhall-lang/dhall-haskell/issues/92

To summarize, those two issues, the current implementation only lets you share types via the import system, like this:

```haskell
$ cat ./MyText
Text
$ cat example
"Hello, world!" : ./MyText
```

**Comment by markandrus** [comment]
Ah, thanks very much @Gabriel439. I do wish there was some syntactic sugar on top of the import system for types that would allow me to land the `MyText` type in the same file, rather than in a separate file, but perhaps that should be discussed elsewhere. I will close this ticket now.

Thank you,
Mark

**Comment by Gabriella439** [comment]
You're welcome!
